[package]
name = "tinyrenderer"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = "line-tables-only"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
env_logger = "0.11.8"
glam = { version = "0.30.5" }
log = "0.4.27"
nom = "8.0.0"
pixels = { git = "https://github.com/parasyte/pixels.git", rev = "21bae15f854186598e21ad508f4068a0ebb26d1c"} 
rand = "0.9.2"
winit = "0.30.12"

[features]
default = []
debug-asserts = ["glam/glam-assert"]
