[package]
name = "tinyrenderer"
version = "0.1.0"
edition = "2024"

[dependencies]
binrw = "0.15.0"
clap = { version = "4.5.45", features = ["derive"] }
glam = { version = "0.30.5", features = ["glam-assert"] }
nom = "8.0.0"
rand = "0.9.2"
